### ISSUE TITLE
Transitions only with hierarchical state machines

### ISSUE THREAD

**Issue by Jasinsky** [FSMLang/FSMLang#21] opened 2023-03-03 16:58 UTC
@9Fingered - 

Is this snippet of FSMLang code valid?
```
machine test
{
	state s1, s2;
	event e1, e2;

	machine sub
	{
		state s3, s4;
		event e3, e4;
		transition[e3,     s3] s4;
         	transition[e4,     s4] s3;
	}
    transition[e1,     s1] s2;
    transition[e2,     s2] s1;
}

```

FSM Lang claims:
```
only one level of sub-machines are currently supported
        line 16 : }
```

**Comment by Jasinsky** [comment] 2023-03-03 18:51
Here is the code snippet which gets successfully compiled:
```
machine test
{
	state s1, s2;
	event e1, e2;

	machine sub
	{
		state s3, s4;
		event e3, e4;
		action a1 [e3,     s3] transition s4;
    	action a2 [e4,     s4] transition s3;
	}
    action a1 [e1,     s1] transition s2;
    action a1 [e2,     s2] transition s1;
}
```

**Comment by 9Fingered** [comment] 2023-03-07 02:59
Duplicate of issue #6

**Comment by 9Fingered** [comment] 2023-03-07 03:02
Duplicate of #6.

**Closed by 9Fingered** 2023-03-07 03:02 UTC
Labels: duplicate
